import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <nav style={{ padding: "1rem", borderBottom: "1px solid #ccc" }}>
      <Link href="/posts" style={{ marginRight: "1rem" }}>
        Home
      </Link>
    </nav>
  );
}

function Footer() {
  return (
    <footer
      style={{
        padding: "1rem",
        borderTop: "1px solid #ccc",
        marginTop: "2rem",
      }}
    >
      <p>© 2024 My Blog by Julia Shark. All rights reserved.</p>
    </footer>
  );
}
